export const SET_TERMS = 'SEARCH_ACTION:SET_TERMS';
export const SET_BRANDS = 'SEARCH_ACTION:SET_BRANDS';
export const SET_STYLES = 'SEARCH_ACTION:SET_STYLES';
export const ON_INITIALIZATION_SUCCESS = 'SEARCH_ACTION:ON_INITIALIZATION_SUCCESS';
